#!/bin/bash

# 📱 Script de Instalação do Android SDK para ToneForge
# Instala Android SDK Command Line Tools e componentes necessários

set -e

# Cores
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

log_success() { echo -e "${GREEN}✅ $1${NC}"; }
log_error() { echo -e "${RED}❌ $1${NC}"; }
log_warning() { echo -e "${YELLOW}⚠️  $1${NC}"; }
log_info() { echo -e "${BLUE}ℹ️  $1${NC}"; }
log_step() { echo -e "${CYAN}🔧 $1${NC}"; }

echo ""
echo "📱 ToneForge - Instalação do Android SDK"
echo "=========================================="
echo ""

# Configurações
ANDROID_SDK_ROOT="$HOME/Android/Sdk"
CMDLINE_TOOLS_VERSION="11076708"  # Latest stable version
CMDLINE_TOOLS_URL="https://dl.google.com/android/repository/commandlinetools-linux-${CMDLINE_TOOLS_VERSION}_latest.zip"

# Componentes necessários para ToneForge
COMPILE_SDK="36"
BUILD_TOOLS="36.0.0"
MIN_SDK="27"
NDK_VERSION="27.2.12479018"  # Latest stable NDK
CMAKE_VERSION="3.22.1"

log_step "Etapa 1/6: Criando diretório do Android SDK..."
mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools"
log_success "Diretório criado: $ANDROID_SDK_ROOT"
echo ""

log_step "Etapa 2/6: Baixando Android Command Line Tools..."
log_info "URL: $CMDLINE_TOOLS_URL"
log_warning "Isso pode demorar alguns minutos (aproximadamente 150MB)..."

TEMP_ZIP="/tmp/cmdline-tools.zip"
if wget -q --show-progress -O "$TEMP_ZIP" "$CMDLINE_TOOLS_URL"; then
    log_success "Download concluído!"
else
    log_error "Falha no download. Verifique sua conexão com a internet."
    exit 1
fi
echo ""

log_step "Etapa 3/6: Extraindo Command Line Tools..."
if unzip -q "$TEMP_ZIP" -d "$ANDROID_SDK_ROOT/cmdline-tools"; then
    # Reorganizar estrutura (o zip vem com pasta 'cmdline-tools')
    mv "$ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools" "$ANDROID_SDK_ROOT/cmdline-tools/latest"
    rm "$TEMP_ZIP"
    log_success "Command Line Tools instalado!"
else
    log_error "Falha ao extrair. Verifique se 'unzip' está instalado."
    exit 1
fi
echo ""

log_step "Etapa 4/6: Configurando variáveis de ambiente..."

export ANDROID_HOME="$ANDROID_SDK_ROOT"
export ANDROID_SDK_ROOT="$ANDROID_SDK_ROOT"
export PATH="$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH"
export PATH="$ANDROID_SDK_ROOT/platform-tools:$PATH"
export PATH="$ANDROID_SDK_ROOT/emulator:$PATH"

log_success "Variáveis configuradas para esta sessão"

# Adicionar ao .bashrc se ainda não estiver
if ! grep -q "ANDROID_HOME" "$HOME/.bashrc"; then
    log_info "Adicionando ao ~/.bashrc..."
    cat >> "$HOME/.bashrc" << EOF

# Android SDK Configuration - ToneForge
export ANDROID_HOME=\$HOME/Android/Sdk
export ANDROID_SDK_ROOT=\$HOME/Android/Sdk
export PATH=\$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:\$PATH
export PATH=\$ANDROID_SDK_ROOT/platform-tools:\$PATH
export PATH=\$ANDROID_SDK_ROOT/emulator:\$PATH
EOF
    log_success "Configuração adicionada ao ~/.bashrc"
else
    log_info "ANDROID_HOME já está no ~/.bashrc"
fi
echo ""

log_step "Etapa 5/6: Instalando componentes do Android SDK..."
log_info "Instalando:"
log_info "  - Android SDK Platform $COMPILE_SDK"
log_info "  - Build Tools $BUILD_TOOLS"
log_info "  - Platform Tools (adb, fastboot)"
log_info "  - NDK $NDK_VERSION (para C++ nativo)"
log_info "  - CMake $CMAKE_VERSION (para compilação C++)"
echo ""
log_warning "Isso pode demorar 5-10 minutos e baixar ~2GB de dados..."
echo ""

# Aceitar licenças automaticamente
yes | sdkmanager --licenses > /dev/null 2>&1 || true

# Instalar componentes
sdkmanager --install \
    "platforms;android-$COMPILE_SDK" \
    "build-tools;$BUILD_TOOLS" \
    "platform-tools" \
    "ndk;$NDK_VERSION" \
    "cmake;$CMAKE_VERSION" 2>&1 | grep -v "Info:"

if [ $? -eq 0 ]; then
    log_success "Componentes instalados com sucesso!"
else
    log_warning "Alguns componentes podem ter falhado. Continue para verificar."
fi
echo ""

log_step "Etapa 6/6: Criando local.properties para o projeto..."
cd /home/thiago/thiago-code/07-entretenimento/ToneForge

cat > local.properties << EOF
## This file is automatically generated by install-android-sdk.sh
## Do NOT check this into version control (already in .gitignore)

# Android SDK location
sdk.dir=$ANDROID_SDK_ROOT

# NDK location (optional, SDK manager handles this)
ndk.dir=$ANDROID_SDK_ROOT/ndk/$NDK_VERSION
EOF

log_success "local.properties criado!"
echo ""

# Verificação final
log_info "Verificando instalação..."
echo ""

echo "📊 Componentes instalados:"
sdkmanager --list_installed 2>/dev/null | grep -E "platforms|build-tools|platform-tools|ndk|cmake" || true
echo ""

echo "🔍 Verificações:"
if [ -f "$ANDROID_SDK_ROOT/platform-tools/adb" ]; then
    log_success "ADB instalado: $($ANDROID_SDK_ROOT/platform-tools/adb --version | head -1)"
else
    log_warning "ADB não encontrado"
fi

if [ -d "$ANDROID_SDK_ROOT/ndk/$NDK_VERSION" ]; then
    log_success "NDK instalado: $NDK_VERSION"
else
    log_warning "NDK não encontrado"
fi

if [ -d "$ANDROID_SDK_ROOT/platforms/android-$COMPILE_SDK" ]; then
    log_success "Android Platform $COMPILE_SDK instalado"
else
    log_warning "Android Platform $COMPILE_SDK não encontrado"
fi

if [ -f "local.properties" ]; then
    log_success "local.properties criado"
    cat local.properties
else
    log_error "local.properties não foi criado"
fi
echo ""

# Resumo final
echo "🎯 INSTALAÇÃO CONCLUÍDA!"
echo "========================"
echo ""
log_success "Android SDK instalado em: $ANDROID_SDK_ROOT"
echo ""
echo "📋 Informações:"
echo "  Android SDK: $ANDROID_SDK_ROOT"
echo "  Compile SDK: API $COMPILE_SDK"
echo "  Build Tools: $BUILD_TOOLS"
echo "  NDK: $NDK_VERSION"
echo "  CMake: $CMAKE_VERSION"
echo ""
echo "🚀 Próximos passos:"
echo "  1. Recarregar shell: source ~/.bashrc"
echo "  2. Compilar projeto: ./gradlew assembleDebug"
echo "  3. Executar testes: ./gradlew test"
echo ""
log_warning "Execute 'source ~/.bashrc' para aplicar as mudanças neste terminal"
echo ""
