// GENERATED FILE. DO NOT EDIT.
// Regenerar via: fvm flutter pub run ffigen --config ffigen.yaml
// ignore_for_file: type=lint, unused_field, unused_element

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: unused_import
import 'dart:ffi' as ffi;

/// FFI bindings para o engine nativo do ToneForge (DSP + Oboe backend).
/// Gerado a partir dos headers em ../engine/include/toneforge/.
///
class ToneforgeEngineBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  ToneforgeEngineBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  ToneforgeEngineBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  /// Controles básicos
  void setGain(double gain) {
    return _setGain(gain);
  }

  late final _setGainPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Float)>>('setGain');
  late final _setGain = _setGainPtr.asFunction<void Function(double)>();

  void setDistortion(double amount) {
    return _setDistortion(amount);
  }

  late final _setDistortionPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Float)>>(
        'setDistortion',
      );
  late final _setDistortion = _setDistortionPtr
      .asFunction<void Function(double)>();

  void setDelay(double time, double feedback) {
    return _setDelay(time, feedback);
  }

  late final _setDelayPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Float, ffi.Float)>>(
        'setDelay',
      );
  late final _setDelay = _setDelayPtr
      .asFunction<void Function(double, double)>();

  void setReverb(double roomSize, double damping) {
    return _setReverb(roomSize, damping);
  }

  late final _setReverbPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Float, ffi.Float)>>(
        'setReverb',
      );
  late final _setReverb = _setReverbPtr
      .asFunction<void Function(double, double)>();

  /// Processamento de áudio
  double processSample(double input) {
    return _processSample(input);
  }

  late final _processSamplePtr =
      _lookup<ffi.NativeFunction<ffi.Float Function(ffi.Float)>>(
        'processSample',
      );
  late final _processSample = _processSamplePtr
      .asFunction<double Function(double)>();

  void processBuffer(
    ffi.Pointer<ffi.Float> input,
    ffi.Pointer<ffi.Float> output,
    int numSamples,
    int inputLength,
    int outputLength,
  ) {
    return _processBuffer(input, output, numSamples, inputLength, outputLength);
  }

  late final _processBufferPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<ffi.Float>,
            ffi.Pointer<ffi.Float>,
            ffi.Int,
            ffi.Int,
            ffi.Int,
          )
        >
      >('processBuffer');
  late final _processBuffer = _processBufferPtr
      .asFunction<
        void Function(
          ffi.Pointer<ffi.Float>,
          ffi.Pointer<ffi.Float>,
          int,
          int,
          int,
        )
      >();

  /// Inicialização e limpeza
  void initAudioEngine() {
    return _initAudioEngine();
  }

  late final _initAudioEnginePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>('initAudioEngine');
  late final _initAudioEngine = _initAudioEnginePtr
      .asFunction<void Function()>();

  void cleanupAudioEngine() {
    return _cleanupAudioEngine();
  }

  late final _cleanupAudioEnginePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>('cleanupAudioEngine');
  late final _cleanupAudioEngine = _cleanupAudioEnginePtr
      .asFunction<void Function()>();

  /// Metrônomo
  void startMetronome(int bpm) {
    return _startMetronome(bpm);
  }

  late final _startMetronomePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int)>>('startMetronome');
  late final _startMetronome = _startMetronomePtr
      .asFunction<void Function(int)>();

  void stopMetronome() {
    return _stopMetronome();
  }

  late final _stopMetronomePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>('stopMetronome');
  late final _stopMetronome = _stopMetronomePtr.asFunction<void Function()>();

  bool isMetronomeActive() {
    return _isMetronomeActive();
  }

  late final _isMetronomeActivePtr =
      _lookup<ffi.NativeFunction<ffi.Bool Function()>>('isMetronomeActive');
  late final _isMetronomeActive = _isMetronomeActivePtr
      .asFunction<bool Function()>();

  void setSampleRate(int rate) {
    return _setSampleRate(rate);
  }

  late final _setSampleRatePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int)>>('setSampleRate');
  late final _setSampleRate = _setSampleRatePtr
      .asFunction<void Function(int)>();

  /// Looper
  void startLooperRecording() {
    return _startLooperRecording();
  }

  late final _startLooperRecordingPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>('startLooperRecording');
  late final _startLooperRecording = _startLooperRecordingPtr
      .asFunction<void Function()>();

  void stopLooperRecording() {
    return _stopLooperRecording();
  }

  late final _stopLooperRecordingPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>('stopLooperRecording');
  late final _stopLooperRecording = _stopLooperRecordingPtr
      .asFunction<void Function()>();

  void startLooperPlayback() {
    return _startLooperPlayback();
  }

  late final _startLooperPlaybackPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>('startLooperPlayback');
  late final _startLooperPlayback = _startLooperPlaybackPtr
      .asFunction<void Function()>();

  void stopLooperPlayback() {
    return _stopLooperPlayback();
  }

  late final _stopLooperPlaybackPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>('stopLooperPlayback');
  late final _stopLooperPlayback = _stopLooperPlaybackPtr
      .asFunction<void Function()>();

  void clearLooper() {
    return _clearLooper();
  }

  late final _clearLooperPtr = _lookup<ffi.NativeFunction<ffi.Void Function()>>(
    'clearLooper',
  );
  late final _clearLooper = _clearLooperPtr.asFunction<void Function()>();

  bool isLooperRecording() {
    return _isLooperRecording();
  }

  late final _isLooperRecordingPtr =
      _lookup<ffi.NativeFunction<ffi.Bool Function()>>('isLooperRecording');
  late final _isLooperRecording = _isLooperRecordingPtr
      .asFunction<bool Function()>();

  bool isLooperPlaying() {
    return _isLooperPlaying();
  }

  late final _isLooperPlayingPtr =
      _lookup<ffi.NativeFunction<ffi.Bool Function()>>('isLooperPlaying');
  late final _isLooperPlaying = _isLooperPlayingPtr
      .asFunction<bool Function()>();

  /// Novas funções para looper avançado
  int getLooperLength() {
    return _getLooperLength();
  }

  late final _getLooperLengthPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function()>>('getLooperLength');
  late final _getLooperLength = _getLooperLengthPtr
      .asFunction<int Function()>();

  int getLooperPosition() {
    return _getLooperPosition();
  }

  late final _getLooperPositionPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function()>>('getLooperPosition');
  late final _getLooperPosition = _getLooperPositionPtr
      .asFunction<int Function()>();

  void setLooperPosition(int position) {
    return _setLooperPosition(position);
  }

  late final _setLooperPositionPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int)>>(
        'setLooperPosition',
      );
  late final _setLooperPosition = _setLooperPositionPtr
      .asFunction<void Function(int)>();

  void setLooperTrackVolume(int trackIndex, double volume) {
    return _setLooperTrackVolume(trackIndex, volume);
  }

  late final _setLooperTrackVolumePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int, ffi.Float)>>(
        'setLooperTrackVolume',
      );
  late final _setLooperTrackVolume = _setLooperTrackVolumePtr
      .asFunction<void Function(int, double)>();

  void setLooperTrackMuted(int trackIndex, bool muted) {
    return _setLooperTrackMuted(trackIndex, muted);
  }

  late final _setLooperTrackMutedPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int, ffi.Bool)>>(
        'setLooperTrackMuted',
      );
  late final _setLooperTrackMuted = _setLooperTrackMutedPtr
      .asFunction<void Function(int, bool)>();

  void setLooperTrackSoloed(int trackIndex, bool soloed) {
    return _setLooperTrackSoloed(trackIndex, soloed);
  }

  late final _setLooperTrackSoloedPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int, ffi.Bool)>>(
        'setLooperTrackSoloed',
      );
  late final _setLooperTrackSoloed = _setLooperTrackSoloedPtr
      .asFunction<void Function(int, bool)>();

  void removeLooperTrack(int trackIndex) {
    return _removeLooperTrack(trackIndex);
  }

  late final _removeLooperTrackPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int)>>(
        'removeLooperTrack',
      );
  late final _removeLooperTrack = _removeLooperTrackPtr
      .asFunction<void Function(int)>();

  void setLooperBPM(int bpm) {
    return _setLooperBPM(bpm);
  }

  late final _setLooperBPMPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int)>>('setLooperBPM');
  late final _setLooperBPM = _setLooperBPMPtr.asFunction<void Function(int)>();

  void setLooperSyncEnabled(bool enabled) {
    return _setLooperSyncEnabled(enabled);
  }

  late final _setLooperSyncEnabledPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Bool)>>(
        'setLooperSyncEnabled',
      );
  late final _setLooperSyncEnabled = _setLooperSyncEnabledPtr
      .asFunction<void Function(bool)>();

  /// Afinador
  void startTuner() {
    return _startTuner();
  }

  late final _startTunerPtr = _lookup<ffi.NativeFunction<ffi.Void Function()>>(
    'startTuner',
  );
  late final _startTuner = _startTunerPtr.asFunction<void Function()>();

  void stopTuner() {
    return _stopTuner();
  }

  late final _stopTunerPtr = _lookup<ffi.NativeFunction<ffi.Void Function()>>(
    'stopTuner',
  );
  late final _stopTuner = _stopTunerPtr.asFunction<void Function()>();

  bool isTunerActive() {
    return _isTunerActive();
  }

  late final _isTunerActivePtr =
      _lookup<ffi.NativeFunction<ffi.Bool Function()>>('isTunerActive');
  late final _isTunerActive = _isTunerActivePtr.asFunction<bool Function()>();

  double getDetectedFrequency() {
    return _getDetectedFrequency();
  }

  late final _getDetectedFrequencyPtr =
      _lookup<ffi.NativeFunction<ffi.Float Function()>>('getDetectedFrequency');
  late final _getDetectedFrequency = _getDetectedFrequencyPtr
      .asFunction<double Function()>();

  void processTunerBuffer(ffi.Pointer<ffi.Float> input, int numSamples) {
    return _processTunerBuffer(input, numSamples);
  }

  late final _processTunerBufferPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Float>, ffi.Int)>
      >('processTunerBuffer');
  late final _processTunerBuffer = _processTunerBufferPtr
      .asFunction<void Function(ffi.Pointer<ffi.Float>, int)>();

  /// Ativação/desativação de efeitos
  void setGainEnabled(bool enabled) {
    return _setGainEnabled(enabled);
  }

  late final _setGainEnabledPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Bool)>>(
        'setGainEnabled',
      );
  late final _setGainEnabled = _setGainEnabledPtr
      .asFunction<void Function(bool)>();

  void setDistortionEnabled(bool enabled) {
    return _setDistortionEnabled(enabled);
  }

  late final _setDistortionEnabledPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Bool)>>(
        'setDistortionEnabled',
      );
  late final _setDistortionEnabled = _setDistortionEnabledPtr
      .asFunction<void Function(bool)>();

  void setDelayEnabled(bool enabled) {
    return _setDelayEnabled(enabled);
  }

  late final _setDelayEnabledPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Bool)>>(
        'setDelayEnabled',
      );
  late final _setDelayEnabled = _setDelayEnabledPtr
      .asFunction<void Function(bool)>();

  void setReverbEnabled(bool enabled) {
    return _setReverbEnabled(enabled);
  }

  late final _setReverbEnabledPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Bool)>>(
        'setReverbEnabled',
      );
  late final _setReverbEnabled = _setReverbEnabledPtr
      .asFunction<void Function(bool)>();

  double getDelayTime() {
    return _getDelayTime();
  }

  late final _getDelayTimePtr =
      _lookup<ffi.NativeFunction<ffi.Float Function()>>('getDelayTime');
  late final _getDelayTime = _getDelayTimePtr.asFunction<double Function()>();

  double getDelayFeedback() {
    return _getDelayFeedback();
  }

  late final _getDelayFeedbackPtr =
      _lookup<ffi.NativeFunction<ffi.Float Function()>>('getDelayFeedback');
  late final _getDelayFeedback = _getDelayFeedbackPtr
      .asFunction<double Function()>();

  double getReverbRoomSize() {
    return _getReverbRoomSize();
  }

  late final _getReverbRoomSizePtr =
      _lookup<ffi.NativeFunction<ffi.Float Function()>>('getReverbRoomSize');
  late final _getReverbRoomSize = _getReverbRoomSizePtr
      .asFunction<double Function()>();

  double getReverbDamping() {
    return _getReverbDamping();
  }

  late final _getReverbDampingPtr =
      _lookup<ffi.NativeFunction<ffi.Float Function()>>('getReverbDamping');
  late final _getReverbDamping = _getReverbDampingPtr
      .asFunction<double Function()>();

  void setEffectOrder(ffi.Pointer<ffi.Pointer<ffi.Char>> order, int count) {
    return _setEffectOrder(order, count);
  }

  late final _setEffectOrderPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<ffi.Pointer<ffi.Char>>, ffi.Int)
        >
      >('setEffectOrder');
  late final _setEffectOrder = _setEffectOrderPtr
      .asFunction<void Function(ffi.Pointer<ffi.Pointer<ffi.Char>>, int)>();

  /// Funções para Oversampling
  void setOversamplingEnabled(bool enabled) {
    return _setOversamplingEnabled(enabled);
  }

  late final _setOversamplingEnabledPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Bool)>>(
        'setOversamplingEnabled',
      );
  late final _setOversamplingEnabled = _setOversamplingEnabledPtr
      .asFunction<void Function(bool)>();

  void setOversamplingFactor(int factor) {
    return _setOversamplingFactor(factor);
  }

  late final _setOversamplingFactorPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int)>>(
        'setOversamplingFactor',
      );
  late final _setOversamplingFactor = _setOversamplingFactorPtr
      .asFunction<void Function(int)>();

  bool isOversamplingEnabled() {
    return _isOversamplingEnabled();
  }

  late final _isOversamplingEnabledPtr =
      _lookup<ffi.NativeFunction<ffi.Bool Function()>>('isOversamplingEnabled');
  late final _isOversamplingEnabled = _isOversamplingEnabledPtr
      .asFunction<bool Function()>();

  int getOversamplingFactor() {
    return _getOversamplingFactor();
  }

  late final _getOversamplingFactorPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function()>>('getOversamplingFactor');
  late final _getOversamplingFactor = _getOversamplingFactorPtr
      .asFunction<int Function()>();

  void setDistortionType(int type) {
    return _setDistortionType(type);
  }

  late final _setDistortionTypePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int)>>(
        'setDistortionType',
      );
  late final _setDistortionType = _setDistortionTypePtr
      .asFunction<void Function(int)>();

  void setDistortionMix(double mix) {
    return _setDistortionMix(mix);
  }

  late final _setDistortionMixPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Float)>>(
        'setDistortionMix',
      );
  late final _setDistortionMix = _setDistortionMixPtr
      .asFunction<void Function(double)>();

  void setDelayMix(double mix) {
    return _setDelayMix(mix);
  }

  late final _setDelayMixPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Float)>>('setDelayMix');
  late final _setDelayMix = _setDelayMixPtr.asFunction<void Function(double)>();

  void setReverbMix(double mix) {
    return _setReverbMix(mix);
  }

  late final _setReverbMixPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Float)>>('setReverbMix');
  late final _setReverbMix = _setReverbMixPtr
      .asFunction<void Function(double)>();

  void setChorusEnabled(bool enabled) {
    return _setChorusEnabled(enabled);
  }

  late final _setChorusEnabledPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Bool)>>(
        'setChorusEnabled',
      );
  late final _setChorusEnabled = _setChorusEnabledPtr
      .asFunction<void Function(bool)>();

  void setChorusDepth(double depth) {
    return _setChorusDepth(depth);
  }

  late final _setChorusDepthPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Float)>>(
        'setChorusDepth',
      );
  late final _setChorusDepth = _setChorusDepthPtr
      .asFunction<void Function(double)>();

  void setChorusRate(double rate) {
    return _setChorusRate(rate);
  }

  late final _setChorusRatePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Float)>>(
        'setChorusRate',
      );
  late final _setChorusRate = _setChorusRatePtr
      .asFunction<void Function(double)>();

  void setChorusMix(double mix) {
    return _setChorusMix(mix);
  }

  late final _setChorusMixPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Float)>>('setChorusMix');
  late final _setChorusMix = _setChorusMixPtr
      .asFunction<void Function(double)>();

  void setFlangerEnabled(bool enabled) {
    return _setFlangerEnabled(enabled);
  }

  late final _setFlangerEnabledPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Bool)>>(
        'setFlangerEnabled',
      );
  late final _setFlangerEnabled = _setFlangerEnabledPtr
      .asFunction<void Function(bool)>();

  void setFlangerDepth(double depth) {
    return _setFlangerDepth(depth);
  }

  late final _setFlangerDepthPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Float)>>(
        'setFlangerDepth',
      );
  late final _setFlangerDepth = _setFlangerDepthPtr
      .asFunction<void Function(double)>();

  void setFlangerRate(double rate) {
    return _setFlangerRate(rate);
  }

  late final _setFlangerRatePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Float)>>(
        'setFlangerRate',
      );
  late final _setFlangerRate = _setFlangerRatePtr
      .asFunction<void Function(double)>();

  void setFlangerFeedback(double feedback) {
    return _setFlangerFeedback(feedback);
  }

  late final _setFlangerFeedbackPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Float)>>(
        'setFlangerFeedback',
      );
  late final _setFlangerFeedback = _setFlangerFeedbackPtr
      .asFunction<void Function(double)>();

  void setFlangerMix(double mix) {
    return _setFlangerMix(mix);
  }

  late final _setFlangerMixPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Float)>>(
        'setFlangerMix',
      );
  late final _setFlangerMix = _setFlangerMixPtr
      .asFunction<void Function(double)>();

  void setPhaserEnabled(bool enabled) {
    return _setPhaserEnabled(enabled);
  }

  late final _setPhaserEnabledPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Bool)>>(
        'setPhaserEnabled',
      );
  late final _setPhaserEnabled = _setPhaserEnabledPtr
      .asFunction<void Function(bool)>();

  void setPhaserDepth(double depth) {
    return _setPhaserDepth(depth);
  }

  late final _setPhaserDepthPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Float)>>(
        'setPhaserDepth',
      );
  late final _setPhaserDepth = _setPhaserDepthPtr
      .asFunction<void Function(double)>();

  void setPhaserRate(double rate) {
    return _setPhaserRate(rate);
  }

  late final _setPhaserRatePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Float)>>(
        'setPhaserRate',
      );
  late final _setPhaserRate = _setPhaserRatePtr
      .asFunction<void Function(double)>();

  void setPhaserFeedback(double feedback) {
    return _setPhaserFeedback(feedback);
  }

  late final _setPhaserFeedbackPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Float)>>(
        'setPhaserFeedback',
      );
  late final _setPhaserFeedback = _setPhaserFeedbackPtr
      .asFunction<void Function(double)>();

  void setPhaserMix(double mix) {
    return _setPhaserMix(mix);
  }

  late final _setPhaserMixPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Float)>>('setPhaserMix');
  late final _setPhaserMix = _setPhaserMixPtr
      .asFunction<void Function(double)>();

  void setEQEnabled(bool enabled) {
    return _setEQEnabled(enabled);
  }

  late final _setEQEnabledPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Bool)>>('setEQEnabled');
  late final _setEQEnabled = _setEQEnabledPtr.asFunction<void Function(bool)>();

  void setEQLow(double gain) {
    return _setEQLow(gain);
  }

  late final _setEQLowPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Float)>>('setEQLow');
  late final _setEQLow = _setEQLowPtr.asFunction<void Function(double)>();

  void setEQMid(double gain) {
    return _setEQMid(gain);
  }

  late final _setEQMidPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Float)>>('setEQMid');
  late final _setEQMid = _setEQMidPtr.asFunction<void Function(double)>();

  void setEQHigh(double gain) {
    return _setEQHigh(gain);
  }

  late final _setEQHighPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Float)>>('setEQHigh');
  late final _setEQHigh = _setEQHighPtr.asFunction<void Function(double)>();

  void setEQMix(double mix) {
    return _setEQMix(mix);
  }

  late final _setEQMixPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Float)>>('setEQMix');
  late final _setEQMix = _setEQMixPtr.asFunction<void Function(double)>();

  void setCompressorEnabled(bool enabled) {
    return _setCompressorEnabled(enabled);
  }

  late final _setCompressorEnabledPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Bool)>>(
        'setCompressorEnabled',
      );
  late final _setCompressorEnabled = _setCompressorEnabledPtr
      .asFunction<void Function(bool)>();

  void setCompressorThreshold(double threshold) {
    return _setCompressorThreshold(threshold);
  }

  late final _setCompressorThresholdPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Float)>>(
        'setCompressorThreshold',
      );
  late final _setCompressorThreshold = _setCompressorThresholdPtr
      .asFunction<void Function(double)>();

  void setCompressorRatio(double ratio) {
    return _setCompressorRatio(ratio);
  }

  late final _setCompressorRatioPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Float)>>(
        'setCompressorRatio',
      );
  late final _setCompressorRatio = _setCompressorRatioPtr
      .asFunction<void Function(double)>();

  void setCompressorAttack(double attack) {
    return _setCompressorAttack(attack);
  }

  late final _setCompressorAttackPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Float)>>(
        'setCompressorAttack',
      );
  late final _setCompressorAttack = _setCompressorAttackPtr
      .asFunction<void Function(double)>();

  void setCompressorRelease(double release) {
    return _setCompressorRelease(release);
  }

  late final _setCompressorReleasePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Float)>>(
        'setCompressorRelease',
      );
  late final _setCompressorRelease = _setCompressorReleasePtr
      .asFunction<void Function(double)>();

  void setCompressorMix(double mix) {
    return _setCompressorMix(mix);
  }

  late final _setCompressorMixPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Float)>>(
        'setCompressorMix',
      );
  late final _setCompressorMix = _setCompressorMixPtr
      .asFunction<void Function(double)>();

  void setDelayTime(double timeMs) {
    return _setDelayTime(timeMs);
  }

  late final _setDelayTimePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Float)>>('setDelayTime');
  late final _setDelayTime = _setDelayTimePtr
      .asFunction<void Function(double)>();

  void setDelaySyncBPM(bool sync) {
    return _setDelaySyncBPM(sync);
  }

  late final _setDelaySyncBPMPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Bool)>>(
        'setDelaySyncBPM',
      );
  late final _setDelaySyncBPM = _setDelaySyncBPMPtr
      .asFunction<void Function(bool)>();

  void setDelayBPM(int bpm) {
    return _setDelayBPM(bpm);
  }

  late final _setDelayBPMPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int)>>('setDelayBPM');
  late final _setDelayBPM = _setDelayBPMPtr.asFunction<void Function(int)>();

  void setReverbType(int type) {
    return _setReverbType(type);
  }

  late final _setReverbTypePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int)>>('setReverbType');
  late final _setReverbType = _setReverbTypePtr
      .asFunction<void Function(int)>();

  ffi.Pointer<ffi.Float> getLooperMix(ffi.Pointer<ffi.Int> outLength) {
    return _getLooperMix(outLength);
  }

  late final _getLooperMixPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Float> Function(ffi.Pointer<ffi.Int>)
        >
      >('getLooperMix');
  late final _getLooperMix = _getLooperMixPtr
      .asFunction<ffi.Pointer<ffi.Float> Function(ffi.Pointer<ffi.Int>)>();

  /// Função para carregar áudio no looper
  void loadLooperFromAudio(ffi.Pointer<ffi.Float> audioData, int length) {
    return _loadLooperFromAudio(audioData, length);
  }

  late final _loadLooperFromAudioPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Float>, ffi.Int)>
      >('loadLooperFromAudio');
  late final _loadLooperFromAudio = _loadLooperFromAudioPtr
      .asFunction<void Function(ffi.Pointer<ffi.Float>, int)>();

  /// Funcionalidades especiais do looper
  void setLooperReverse(bool enabled) {
    return _setLooperReverse(enabled);
  }

  late final _setLooperReversePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Bool)>>(
        'setLooperReverse',
      );
  late final _setLooperReverse = _setLooperReversePtr
      .asFunction<void Function(bool)>();

  void setLooperSpeed(double speed) {
    return _setLooperSpeed(speed);
  }

  late final _setLooperSpeedPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Float)>>(
        'setLooperSpeed',
      );
  late final _setLooperSpeed = _setLooperSpeedPtr
      .asFunction<void Function(double)>();

  void setLooperPitchShift(double semitones) {
    return _setLooperPitchShift(semitones);
  }

  late final _setLooperPitchShiftPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Float)>>(
        'setLooperPitchShift',
      );
  late final _setLooperPitchShift = _setLooperPitchShiftPtr
      .asFunction<void Function(double)>();

  void setLooperStutter(bool enabled, double rate) {
    return _setLooperStutter(enabled, rate);
  }

  late final _setLooperStutterPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Bool, ffi.Float)>>(
        'setLooperStutter',
      );
  late final _setLooperStutter = _setLooperStutterPtr
      .asFunction<void Function(bool, double)>();

  bool isLooperReverseEnabled() {
    return _isLooperReverseEnabled();
  }

  late final _isLooperReverseEnabledPtr =
      _lookup<ffi.NativeFunction<ffi.Bool Function()>>(
        'isLooperReverseEnabled',
      );
  late final _isLooperReverseEnabled = _isLooperReverseEnabledPtr
      .asFunction<bool Function()>();

  double getLooperSpeed() {
    return _getLooperSpeed();
  }

  late final _getLooperSpeedPtr =
      _lookup<ffi.NativeFunction<ffi.Float Function()>>('getLooperSpeed');
  late final _getLooperSpeed = _getLooperSpeedPtr
      .asFunction<double Function()>();

  double getLooperPitchShift() {
    return _getLooperPitchShift();
  }

  late final _getLooperPitchShiftPtr =
      _lookup<ffi.NativeFunction<ffi.Float Function()>>('getLooperPitchShift');
  late final _getLooperPitchShift = _getLooperPitchShiftPtr
      .asFunction<double Function()>();

  bool isLooperStutterEnabled() {
    return _isLooperStutterEnabled();
  }

  late final _isLooperStutterEnabledPtr =
      _lookup<ffi.NativeFunction<ffi.Bool Function()>>(
        'isLooperStutterEnabled',
      );
  late final _isLooperStutterEnabled = _isLooperStutterEnabledPtr
      .asFunction<bool Function()>();

  double getLooperStutterRate() {
    return _getLooperStutterRate();
  }

  late final _getLooperStutterRatePtr =
      _lookup<ffi.NativeFunction<ffi.Float Function()>>('getLooperStutterRate');
  late final _getLooperStutterRate = _getLooperStutterRatePtr
      .asFunction<double Function()>();

  /// Funcionalidade de Slicing
  void setLooperSlicingEnabled(bool enabled) {
    return _setLooperSlicingEnabled(enabled);
  }

  late final _setLooperSlicingEnabledPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Bool)>>(
        'setLooperSlicingEnabled',
      );
  late final _setLooperSlicingEnabled = _setLooperSlicingEnabledPtr
      .asFunction<void Function(bool)>();

  void setLooperSlicePoints(ffi.Pointer<ffi.Int> points, int numPoints) {
    return _setLooperSlicePoints(points, numPoints);
  }

  late final _setLooperSlicePointsPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Int>, ffi.Int)>
      >('setLooperSlicePoints');
  late final _setLooperSlicePoints = _setLooperSlicePointsPtr
      .asFunction<void Function(ffi.Pointer<ffi.Int>, int)>();

  void setLooperSliceLength(int length) {
    return _setLooperSliceLength(length);
  }

  late final _setLooperSliceLengthPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int)>>(
        'setLooperSliceLength',
      );
  late final _setLooperSliceLength = _setLooperSliceLengthPtr
      .asFunction<void Function(int)>();

  bool isLooperSlicingEnabled() {
    return _isLooperSlicingEnabled();
  }

  late final _isLooperSlicingEnabledPtr =
      _lookup<ffi.NativeFunction<ffi.Bool Function()>>(
        'isLooperSlicingEnabled',
      );
  late final _isLooperSlicingEnabled = _isLooperSlicingEnabledPtr
      .asFunction<bool Function()>();

  int getLooperSliceLength() {
    return _getLooperSliceLength();
  }

  late final _getLooperSliceLengthPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function()>>('getLooperSliceLength');
  late final _getLooperSliceLength = _getLooperSliceLengthPtr
      .asFunction<int Function()>();

  int getLooperNumSlices() {
    return _getLooperNumSlices();
  }

  late final _getLooperNumSlicesPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function()>>('getLooperNumSlices');
  late final _getLooperNumSlices = _getLooperNumSlicesPtr
      .asFunction<int Function()>();

  void setLooperSliceOrder(ffi.Pointer<ffi.Int> order, int numSlices) {
    return _setLooperSliceOrder(order, numSlices);
  }

  late final _setLooperSliceOrderPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Int>, ffi.Int)>
      >('setLooperSliceOrder');
  late final _setLooperSliceOrder = _setLooperSliceOrderPtr
      .asFunction<void Function(ffi.Pointer<ffi.Int>, int)>();

  void randomizeLooperSlices() {
    return _randomizeLooperSlices();
  }

  late final _randomizeLooperSlicesPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>('randomizeLooperSlices');
  late final _randomizeLooperSlices = _randomizeLooperSlicesPtr
      .asFunction<void Function()>();

  void reverseLooperSlices() {
    return _reverseLooperSlices();
  }

  late final _reverseLooperSlicesPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>('reverseLooperSlices');
  late final _reverseLooperSlices = _reverseLooperSlicesPtr
      .asFunction<void Function()>();

  /// Funções de edição do looper
  void cutLooperRegion(double start, double end) {
    return _cutLooperRegion(start, end);
  }

  late final _cutLooperRegionPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Float, ffi.Float)>>(
        'cutLooperRegion',
      );
  late final _cutLooperRegion = _cutLooperRegionPtr
      .asFunction<void Function(double, double)>();

  void applyLooperFadeIn(double start, double end) {
    return _applyLooperFadeIn(start, end);
  }

  late final _applyLooperFadeInPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Float, ffi.Float)>>(
        'applyLooperFadeIn',
      );
  late final _applyLooperFadeIn = _applyLooperFadeInPtr
      .asFunction<void Function(double, double)>();

  void applyLooperFadeOut(double start, double end) {
    return _applyLooperFadeOut(start, end);
  }

  late final _applyLooperFadeOutPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Float, ffi.Float)>>(
        'applyLooperFadeOut',
      );
  late final _applyLooperFadeOut = _applyLooperFadeOutPtr
      .asFunction<void Function(double, double)>();

  /// Compressão automática para looper
  void setLooperAutoCompression(bool enabled) {
    return _setLooperAutoCompression(enabled);
  }

  late final _setLooperAutoCompressionPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Bool)>>(
        'setLooperAutoCompression',
      );
  late final _setLooperAutoCompression = _setLooperAutoCompressionPtr
      .asFunction<void Function(bool)>();

  void setLooperCompressionThreshold(double threshold) {
    return _setLooperCompressionThreshold(threshold);
  }

  late final _setLooperCompressionThresholdPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Float)>>(
        'setLooperCompressionThreshold',
      );
  late final _setLooperCompressionThreshold = _setLooperCompressionThresholdPtr
      .asFunction<void Function(double)>();

  void setLooperCompressionRatio(double ratio) {
    return _setLooperCompressionRatio(ratio);
  }

  late final _setLooperCompressionRatioPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Float)>>(
        'setLooperCompressionRatio',
      );
  late final _setLooperCompressionRatio = _setLooperCompressionRatioPtr
      .asFunction<void Function(double)>();

  void setLooperCompressionAttack(double attack) {
    return _setLooperCompressionAttack(attack);
  }

  late final _setLooperCompressionAttackPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Float)>>(
        'setLooperCompressionAttack',
      );
  late final _setLooperCompressionAttack = _setLooperCompressionAttackPtr
      .asFunction<void Function(double)>();

  void setLooperCompressionRelease(double release) {
    return _setLooperCompressionRelease(release);
  }

  late final _setLooperCompressionReleasePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Float)>>(
        'setLooperCompressionRelease',
      );
  late final _setLooperCompressionRelease = _setLooperCompressionReleasePtr
      .asFunction<void Function(double)>();

  bool isLooperAutoCompressionEnabled() {
    return _isLooperAutoCompressionEnabled();
  }

  late final _isLooperAutoCompressionEnabledPtr =
      _lookup<ffi.NativeFunction<ffi.Bool Function()>>(
        'isLooperAutoCompressionEnabled',
      );
  late final _isLooperAutoCompressionEnabled =
      _isLooperAutoCompressionEnabledPtr.asFunction<bool Function()>();

  double getLooperCompressionThreshold() {
    return _getLooperCompressionThreshold();
  }

  late final _getLooperCompressionThresholdPtr =
      _lookup<ffi.NativeFunction<ffi.Float Function()>>(
        'getLooperCompressionThreshold',
      );
  late final _getLooperCompressionThreshold = _getLooperCompressionThresholdPtr
      .asFunction<double Function()>();

  double getLooperCompressionRatio() {
    return _getLooperCompressionRatio();
  }

  late final _getLooperCompressionRatioPtr =
      _lookup<ffi.NativeFunction<ffi.Float Function()>>(
        'getLooperCompressionRatio',
      );
  late final _getLooperCompressionRatio = _getLooperCompressionRatioPtr
      .asFunction<double Function()>();

  double getLooperCompressionAttack() {
    return _getLooperCompressionAttack();
  }

  late final _getLooperCompressionAttackPtr =
      _lookup<ffi.NativeFunction<ffi.Float Function()>>(
        'getLooperCompressionAttack',
      );
  late final _getLooperCompressionAttack = _getLooperCompressionAttackPtr
      .asFunction<double Function()>();

  double getLooperCompressionRelease() {
    return _getLooperCompressionRelease();
  }

  late final _getLooperCompressionReleasePtr =
      _lookup<ffi.NativeFunction<ffi.Float Function()>>(
        'getLooperCompressionRelease',
      );
  late final _getLooperCompressionRelease = _getLooperCompressionReleasePtr
      .asFunction<double Function()>();

  /// Normalização automática
  void setLooperAutoNormalization(bool enabled) {
    return _setLooperAutoNormalization(enabled);
  }

  late final _setLooperAutoNormalizationPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Bool)>>(
        'setLooperAutoNormalization',
      );
  late final _setLooperAutoNormalization = _setLooperAutoNormalizationPtr
      .asFunction<void Function(bool)>();

  void setLooperNormalizationTarget(double target) {
    return _setLooperNormalizationTarget(target);
  }

  late final _setLooperNormalizationTargetPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Float)>>(
        'setLooperNormalizationTarget',
      );
  late final _setLooperNormalizationTarget = _setLooperNormalizationTargetPtr
      .asFunction<void Function(double)>();

  bool isLooperAutoNormalizationEnabled() {
    return _isLooperAutoNormalizationEnabled();
  }

  late final _isLooperAutoNormalizationEnabledPtr =
      _lookup<ffi.NativeFunction<ffi.Bool Function()>>(
        'isLooperAutoNormalizationEnabled',
      );
  late final _isLooperAutoNormalizationEnabled =
      _isLooperAutoNormalizationEnabledPtr.asFunction<bool Function()>();

  double getLooperNormalizationTarget() {
    return _getLooperNormalizationTarget();
  }

  late final _getLooperNormalizationTargetPtr =
      _lookup<ffi.NativeFunction<ffi.Float Function()>>(
        'getLooperNormalizationTarget',
      );
  late final _getLooperNormalizationTarget = _getLooperNormalizationTargetPtr
      .asFunction<double Function()>();

  /// Filtros para looper
  void setLooperLowPassFilter(bool enabled) {
    return _setLooperLowPassFilter(enabled);
  }

  late final _setLooperLowPassFilterPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Bool)>>(
        'setLooperLowPassFilter',
      );
  late final _setLooperLowPassFilter = _setLooperLowPassFilterPtr
      .asFunction<void Function(bool)>();

  void setLooperLowPassFrequency(double frequency) {
    return _setLooperLowPassFrequency(frequency);
  }

  late final _setLooperLowPassFrequencyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Float)>>(
        'setLooperLowPassFrequency',
      );
  late final _setLooperLowPassFrequency = _setLooperLowPassFrequencyPtr
      .asFunction<void Function(double)>();

  void setLooperHighPassFilter(bool enabled) {
    return _setLooperHighPassFilter(enabled);
  }

  late final _setLooperHighPassFilterPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Bool)>>(
        'setLooperHighPassFilter',
      );
  late final _setLooperHighPassFilter = _setLooperHighPassFilterPtr
      .asFunction<void Function(bool)>();

  void setLooperHighPassFrequency(double frequency) {
    return _setLooperHighPassFrequency(frequency);
  }

  late final _setLooperHighPassFrequencyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Float)>>(
        'setLooperHighPassFrequency',
      );
  late final _setLooperHighPassFrequency = _setLooperHighPassFrequencyPtr
      .asFunction<void Function(double)>();

  bool isLooperLowPassEnabled() {
    return _isLooperLowPassEnabled();
  }

  late final _isLooperLowPassEnabledPtr =
      _lookup<ffi.NativeFunction<ffi.Bool Function()>>(
        'isLooperLowPassEnabled',
      );
  late final _isLooperLowPassEnabled = _isLooperLowPassEnabledPtr
      .asFunction<bool Function()>();

  bool isLooperHighPassEnabled() {
    return _isLooperHighPassEnabled();
  }

  late final _isLooperHighPassEnabledPtr =
      _lookup<ffi.NativeFunction<ffi.Bool Function()>>(
        'isLooperHighPassEnabled',
      );
  late final _isLooperHighPassEnabled = _isLooperHighPassEnabledPtr
      .asFunction<bool Function()>();

  double getLooperLowPassFrequency() {
    return _getLooperLowPassFrequency();
  }

  late final _getLooperLowPassFrequencyPtr =
      _lookup<ffi.NativeFunction<ffi.Float Function()>>(
        'getLooperLowPassFrequency',
      );
  late final _getLooperLowPassFrequency = _getLooperLowPassFrequencyPtr
      .asFunction<double Function()>();

  double getLooperHighPassFrequency() {
    return _getLooperHighPassFrequency();
  }

  late final _getLooperHighPassFrequencyPtr =
      _lookup<ffi.NativeFunction<ffi.Float Function()>>(
        'getLooperHighPassFrequency',
      );
  late final _getLooperHighPassFrequency = _getLooperHighPassFrequencyPtr
      .asFunction<double Function()>();

  /// Reverb de cauda entre loops
  void setLooperReverbTail(bool enabled) {
    return _setLooperReverbTail(enabled);
  }

  late final _setLooperReverbTailPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Bool)>>(
        'setLooperReverbTail',
      );
  late final _setLooperReverbTail = _setLooperReverbTailPtr
      .asFunction<void Function(bool)>();

  void setLooperReverbTailDecay(double decay) {
    return _setLooperReverbTailDecay(decay);
  }

  late final _setLooperReverbTailDecayPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Float)>>(
        'setLooperReverbTailDecay',
      );
  late final _setLooperReverbTailDecay = _setLooperReverbTailDecayPtr
      .asFunction<void Function(double)>();

  void setLooperReverbTailMix(double mix) {
    return _setLooperReverbTailMix(mix);
  }

  late final _setLooperReverbTailMixPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Float)>>(
        'setLooperReverbTailMix',
      );
  late final _setLooperReverbTailMix = _setLooperReverbTailMixPtr
      .asFunction<void Function(double)>();

  bool isLooperReverbTailEnabled() {
    return _isLooperReverbTailEnabled();
  }

  late final _isLooperReverbTailEnabledPtr =
      _lookup<ffi.NativeFunction<ffi.Bool Function()>>(
        'isLooperReverbTailEnabled',
      );
  late final _isLooperReverbTailEnabled = _isLooperReverbTailEnabledPtr
      .asFunction<bool Function()>();

  double getLooperReverbTailDecay() {
    return _getLooperReverbTailDecay();
  }

  late final _getLooperReverbTailDecayPtr =
      _lookup<ffi.NativeFunction<ffi.Float Function()>>(
        'getLooperReverbTailDecay',
      );
  late final _getLooperReverbTailDecay = _getLooperReverbTailDecayPtr
      .asFunction<double Function()>();

  double getLooperReverbTailMix() {
    return _getLooperReverbTailMix();
  }

  late final _getLooperReverbTailMixPtr =
      _lookup<ffi.NativeFunction<ffi.Float Function()>>(
        'getLooperReverbTailMix',
      );
  late final _getLooperReverbTailMix = _getLooperReverbTailMixPtr
      .asFunction<double Function()>();

  /// Quantização
  void setLooperQuantization(bool enabled) {
    return _setLooperQuantization(enabled);
  }

  late final _setLooperQuantizationPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Bool)>>(
        'setLooperQuantization',
      );
  late final _setLooperQuantization = _setLooperQuantizationPtr
      .asFunction<void Function(bool)>();

  void setLooperQuantizationGrid(double gridSize) {
    return _setLooperQuantizationGrid(gridSize);
  }

  late final _setLooperQuantizationGridPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Float)>>(
        'setLooperQuantizationGrid',
      );
  late final _setLooperQuantizationGrid = _setLooperQuantizationGridPtr
      .asFunction<void Function(double)>();

  bool isLooperQuantizationEnabled() {
    return _isLooperQuantizationEnabled();
  }

  late final _isLooperQuantizationEnabledPtr =
      _lookup<ffi.NativeFunction<ffi.Bool Function()>>(
        'isLooperQuantizationEnabled',
      );
  late final _isLooperQuantizationEnabled = _isLooperQuantizationEnabledPtr
      .asFunction<bool Function()>();

  double getLooperQuantizationGrid() {
    return _getLooperQuantizationGrid();
  }

  late final _getLooperQuantizationGridPtr =
      _lookup<ffi.NativeFunction<ffi.Float Function()>>(
        'getLooperQuantizationGrid',
      );
  late final _getLooperQuantizationGrid = _getLooperQuantizationGridPtr
      .asFunction<double Function()>();

  /// Fade In/Out automático
  void setLooperAutoFadeIn(bool enabled) {
    return _setLooperAutoFadeIn(enabled);
  }

  late final _setLooperAutoFadeInPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Bool)>>(
        'setLooperAutoFadeIn',
      );
  late final _setLooperAutoFadeIn = _setLooperAutoFadeInPtr
      .asFunction<void Function(bool)>();

  void setLooperAutoFadeOut(bool enabled) {
    return _setLooperAutoFadeOut(enabled);
  }

  late final _setLooperAutoFadeOutPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Bool)>>(
        'setLooperAutoFadeOut',
      );
  late final _setLooperAutoFadeOut = _setLooperAutoFadeOutPtr
      .asFunction<void Function(bool)>();

  void setLooperFadeInDuration(double duration) {
    return _setLooperFadeInDuration(duration);
  }

  late final _setLooperFadeInDurationPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Float)>>(
        'setLooperFadeInDuration',
      );
  late final _setLooperFadeInDuration = _setLooperFadeInDurationPtr
      .asFunction<void Function(double)>();

  void setLooperFadeOutDuration(double duration) {
    return _setLooperFadeOutDuration(duration);
  }

  late final _setLooperFadeOutDurationPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Float)>>(
        'setLooperFadeOutDuration',
      );
  late final _setLooperFadeOutDuration = _setLooperFadeOutDurationPtr
      .asFunction<void Function(double)>();

  bool isLooperAutoFadeInEnabled() {
    return _isLooperAutoFadeInEnabled();
  }

  late final _isLooperAutoFadeInEnabledPtr =
      _lookup<ffi.NativeFunction<ffi.Bool Function()>>(
        'isLooperAutoFadeInEnabled',
      );
  late final _isLooperAutoFadeInEnabled = _isLooperAutoFadeInEnabledPtr
      .asFunction<bool Function()>();

  bool isLooperAutoFadeOutEnabled() {
    return _isLooperAutoFadeOutEnabled();
  }

  late final _isLooperAutoFadeOutEnabledPtr =
      _lookup<ffi.NativeFunction<ffi.Bool Function()>>(
        'isLooperAutoFadeOutEnabled',
      );
  late final _isLooperAutoFadeOutEnabled = _isLooperAutoFadeOutEnabledPtr
      .asFunction<bool Function()>();

  double getLooperFadeInDuration() {
    return _getLooperFadeInDuration();
  }

  late final _getLooperFadeInDurationPtr =
      _lookup<ffi.NativeFunction<ffi.Float Function()>>(
        'getLooperFadeInDuration',
      );
  late final _getLooperFadeInDuration = _getLooperFadeInDurationPtr
      .asFunction<double Function()>();

  double getLooperFadeOutDuration() {
    return _getLooperFadeOutDuration();
  }

  late final _getLooperFadeOutDurationPtr =
      _lookup<ffi.NativeFunction<ffi.Float Function()>>(
        'getLooperFadeOutDuration',
      );
  late final _getLooperFadeOutDuration = _getLooperFadeOutDurationPtr
      .asFunction<double Function()>();

  /// Integração MIDI
  void setLooperMidiEnabled(bool enabled) {
    return _setLooperMidiEnabled(enabled);
  }

  late final _setLooperMidiEnabledPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Bool)>>(
        'setLooperMidiEnabled',
      );
  late final _setLooperMidiEnabled = _setLooperMidiEnabledPtr
      .asFunction<void Function(bool)>();

  void setLooperMidiChannel(int channel) {
    return _setLooperMidiChannel(channel);
  }

  late final _setLooperMidiChannelPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int)>>(
        'setLooperMidiChannel',
      );
  late final _setLooperMidiChannel = _setLooperMidiChannelPtr
      .asFunction<void Function(int)>();

  void setLooperMidiCCMapping(int ccNumber, int function) {
    return _setLooperMidiCCMapping(ccNumber, function);
  }

  late final _setLooperMidiCCMappingPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int, ffi.Int)>>(
        'setLooperMidiCCMapping',
      );
  late final _setLooperMidiCCMapping = _setLooperMidiCCMappingPtr
      .asFunction<void Function(int, int)>();

  bool isLooperMidiEnabled() {
    return _isLooperMidiEnabled();
  }

  late final _isLooperMidiEnabledPtr =
      _lookup<ffi.NativeFunction<ffi.Bool Function()>>('isLooperMidiEnabled');
  late final _isLooperMidiEnabled = _isLooperMidiEnabledPtr
      .asFunction<bool Function()>();

  int getLooperMidiChannel() {
    return _getLooperMidiChannel();
  }

  late final _getLooperMidiChannelPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function()>>('getLooperMidiChannel');
  late final _getLooperMidiChannel = _getLooperMidiChannelPtr
      .asFunction<int Function()>();

  void processLooperMidiMessage(int status, int data1, int data2) {
    return _processLooperMidiMessage(status, data1, data2);
  }

  late final _processLooperMidiMessagePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int, ffi.Int, ffi.Int)>>(
        'processLooperMidiMessage',
      );
  late final _processLooperMidiMessage = _processLooperMidiMessagePtr
      .asFunction<void Function(int, int, int)>();

  /// Notificações
  void setLooperNotificationEnabled(bool enabled) {
    return _setLooperNotificationEnabled(enabled);
  }

  late final _setLooperNotificationEnabledPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Bool)>>(
        'setLooperNotificationEnabled',
      );
  late final _setLooperNotificationEnabled = _setLooperNotificationEnabledPtr
      .asFunction<void Function(bool)>();

  void setLooperNotificationControls(bool showControls) {
    return _setLooperNotificationControls(showControls);
  }

  late final _setLooperNotificationControlsPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Bool)>>(
        'setLooperNotificationControls',
      );
  late final _setLooperNotificationControls = _setLooperNotificationControlsPtr
      .asFunction<void Function(bool)>();

  bool isLooperNotificationEnabled() {
    return _isLooperNotificationEnabled();
  }

  late final _isLooperNotificationEnabledPtr =
      _lookup<ffi.NativeFunction<ffi.Bool Function()>>(
        'isLooperNotificationEnabled',
      );
  late final _isLooperNotificationEnabled = _isLooperNotificationEnabledPtr
      .asFunction<bool Function()>();

  bool isLooperNotificationControlsEnabled() {
    return _isLooperNotificationControlsEnabled();
  }

  late final _isLooperNotificationControlsEnabledPtr =
      _lookup<ffi.NativeFunction<ffi.Bool Function()>>(
        'isLooperNotificationControlsEnabled',
      );
  late final _isLooperNotificationControlsEnabled =
      _isLooperNotificationControlsEnabledPtr.asFunction<bool Function()>();

  void updateLooperNotificationState() {
    return _updateLooperNotificationState();
  }

  late final _updateLooperNotificationStatePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>(
        'updateLooperNotificationState',
      );
  late final _updateLooperNotificationState = _updateLooperNotificationStatePtr
      .asFunction<void Function()>();

  /// Declarações para o metrônomo
  void setMetronomeVolume(double volume) {
    return _setMetronomeVolume(volume);
  }

  late final _setMetronomeVolumePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Float)>>(
        'setMetronomeVolume',
      );
  late final _setMetronomeVolume = _setMetronomeVolumePtr
      .asFunction<void Function(double)>();

  void setMetronomeTimeSignature(int beats) {
    return _setMetronomeTimeSignature(beats);
  }

  late final _setMetronomeTimeSignaturePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int)>>(
        'setMetronomeTimeSignature',
      );
  late final _setMetronomeTimeSignature = _setMetronomeTimeSignaturePtr
      .asFunction<void Function(int)>();

  /// Métodos getter para parâmetros de efeitos
  double getGain() {
    return _getGain();
  }

  late final _getGainPtr = _lookup<ffi.NativeFunction<ffi.Float Function()>>(
    'getGain',
  );
  late final _getGain = _getGainPtr.asFunction<double Function()>();

  double getDistortion() {
    return _getDistortion();
  }

  late final _getDistortionPtr =
      _lookup<ffi.NativeFunction<ffi.Float Function()>>('getDistortion');
  late final _getDistortion = _getDistortionPtr.asFunction<double Function()>();

  /// Abre streams Oboe e começa a processar. Retorna 0 em sucesso, código de
  /// erro Oboe < 0 caso falhe. sampleRate 0 deixa o Oboe escolher a taxa nativa
  /// do device. framesPerCallback 0 deixa o Oboe usar o burst nativo.
  int audio_engine_start(int sampleRate, int framesPerCallback) {
    return _audio_engine_start(sampleRate, framesPerCallback);
  }

  late final _audio_engine_startPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int, ffi.Int)>>(
        'audio_engine_start',
      );
  late final _audio_engine_start = _audio_engine_startPtr
      .asFunction<int Function(int, int)>();

  /// Para e fecha os streams. Idempotente.
  void audio_engine_stop() {
    return _audio_engine_stop();
  }

  late final _audio_engine_stopPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>('audio_engine_stop');
  late final _audio_engine_stop = _audio_engine_stopPtr
      .asFunction<void Function()>();

  /// True se há streams abertas e rodando.
  bool audio_engine_is_running() {
    return _audio_engine_is_running();
  }

  late final _audio_engine_is_runningPtr =
      _lookup<ffi.NativeFunction<ffi.Bool Function()>>(
        'audio_engine_is_running',
      );
  late final _audio_engine_is_running = _audio_engine_is_runningPtr
      .asFunction<bool Function()>();

  /// Latência de round-trip estimada em milissegundos (input + output). -1 se
  /// não disponível.
  double audio_engine_get_latency_ms() {
    return _audio_engine_get_latency_ms();
  }

  late final _audio_engine_get_latency_msPtr =
      _lookup<ffi.NativeFunction<ffi.Double Function()>>(
        'audio_engine_get_latency_ms',
      );
  late final _audio_engine_get_latency_ms = _audio_engine_get_latency_msPtr
      .asFunction<double Function()>();

  /// Contador de underruns acumulados desde o último start. Para telemetria do
  /// benchmark.
  int audio_engine_get_xrun_count() {
    return _audio_engine_get_xrun_count();
  }

  late final _audio_engine_get_xrun_countPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function()>>(
        'audio_engine_get_xrun_count',
      );
  late final _audio_engine_get_xrun_count = _audio_engine_get_xrun_countPtr
      .asFunction<int Function()>();

  /// Sample rate efetivo escolhido pelo Oboe (pode diferir do solicitado). 0 se
  /// não rodando.
  int audio_engine_get_sample_rate() {
    return _audio_engine_get_sample_rate();
  }

  late final _audio_engine_get_sample_ratePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function()>>(
        'audio_engine_get_sample_rate',
      );
  late final _audio_engine_get_sample_rate = _audio_engine_get_sample_ratePtr
      .asFunction<int Function()>();
}
