name: Android CI/CD

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle (ignore lint errors)
      run: ./gradlew build --continue
      
    - name: Build Release APK
      run: ./gradlew assembleRelease --continue
      
    - name: Build Debug APK
      run: ./gradlew assembleDebug --continue
      
    - name: Check if Release APK exists
      run: |
        if [ -f "app/build/outputs/apk/release/app-release.apk" ]; then
          echo "Release APK found"
          echo "RELEASE_APK_EXISTS=true" >> $GITHUB_ENV
        else
          echo "Release APK not found, will use debug APK"
          echo "RELEASE_APK_EXISTS=false" >> $GITHUB_ENV
        fi
        
    - name: Upload Release APK
      if: env.RELEASE_APK_EXISTS == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: ToneForge-Release
        path: app/build/outputs/apk/release/app-release.apk
        
    - name: Upload Debug APK as Release
      if: env.RELEASE_APK_EXISTS == 'false'
      uses: actions/upload-artifact@v4
      with:
        name: ToneForge-Release
        path: app/build/outputs/apk/debug/app-debug.apk
        
    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: ToneForge-Debug
        path: app/build/outputs/apk/debug/app-debug.apk

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
    - name: Download Release APK
      uses: actions/download-artifact@v4
      with:
        name: ToneForge-Release
        
    - name: List downloaded files
      run: ls -la
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: app-debug.apk
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
