name: Clang Static Analyzer

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  clang-analyzer:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y clang cmake build-essential
    
    - name: Run Clang Static Analyzer
      run: |
        # Configurar CMake com Clang
        mkdir build
        cd build
        cmake -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ \
              -DCMAKE_BUILD_TYPE=Debug \
              -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
              ../app/src/main/cpp
        
        # Executar análise estática
        scan-build -o clang-analysis make
        
        # Gerar relatório HTML
        if [ -d "clang-analysis" ]; then
          echo "## Clang Static Analyzer Results" > clang-report.md
          echo "" >> clang-report.md
          echo "Análise concluída. Verifique os arquivos HTML em clang-analysis/ para detalhes." >> clang-report.md
        else
          echo "## Clang Static Analyzer Results" > clang-report.md
          echo "" >> clang-report.md
          echo "✅ Nenhum problema encontrado!" >> clang-report.md
        fi
    
    - name: Upload Clang analysis results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: clang-analysis
        path: build/clang-analysis/
    
    - name: Upload Clang report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: clang-report
        path: build/clang-report.md 