name: SpotBugs Security Analysis

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  spotbugs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build project
      run: ./gradlew build
    
    - name: Run SpotBugs
      run: |
        # Instalar SpotBugs
        wget https://github.com/spotbugs/spotbugs/releases/download/4.7.3/spotbugs-4.7.3.tgz
        tar -xzf spotbugs-4.7.3.tgz
        export PATH=$PATH:./spotbugs-4.7.3/bin
        
        # Executar análise
        spotbugs -textui -html -outputDir spotbugs-report \
          -include spotbugs-include.xml \
          app/build/intermediates/javac/debug/
    
    - name: Upload SpotBugs report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: spotbugs-report
        path: spotbugs-report/ 